[2025-01-30T11:57:18.322+0000] {processor.py:186} INFO - Started process (PID=271) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T11:57:18.323+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T11:57:18.328+0000] {logging_mixin.py:190} INFO - [2025-01-30T11:57:18.327+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T11:57:18.336+0000] {logging_mixin.py:190} INFO - [2025-01-30T11:57:18.333+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T11:57:18.337+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T11:57:18.367+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.063 seconds
[2025-01-30T11:57:48.650+0000] {processor.py:186} INFO - Started process (PID=278) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T11:57:48.651+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T11:57:48.659+0000] {logging_mixin.py:190} INFO - [2025-01-30T11:57:48.658+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T11:57:48.671+0000] {logging_mixin.py:190} INFO - [2025-01-30T11:57:48.668+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T11:57:48.673+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T11:57:48.714+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.076 seconds
[2025-01-30T11:58:19.010+0000] {processor.py:186} INFO - Started process (PID=285) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T11:58:19.012+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T11:58:19.018+0000] {logging_mixin.py:190} INFO - [2025-01-30T11:58:19.017+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T11:58:19.031+0000] {logging_mixin.py:190} INFO - [2025-01-30T11:58:19.028+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T11:58:19.033+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T11:58:19.075+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.081 seconds
[2025-01-30T11:58:49.346+0000] {processor.py:186} INFO - Started process (PID=292) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T11:58:49.349+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T11:58:49.355+0000] {logging_mixin.py:190} INFO - [2025-01-30T11:58:49.354+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T11:58:49.367+0000] {logging_mixin.py:190} INFO - [2025-01-30T11:58:49.365+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T11:58:49.369+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T11:58:49.404+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.074 seconds
[2025-01-30T11:59:19.696+0000] {processor.py:186} INFO - Started process (PID=299) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T11:59:19.698+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T11:59:19.705+0000] {logging_mixin.py:190} INFO - [2025-01-30T11:59:19.704+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T11:59:19.717+0000] {logging_mixin.py:190} INFO - [2025-01-30T11:59:19.714+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T11:59:19.719+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T11:59:19.760+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.077 seconds
[2025-01-30T11:59:50.053+0000] {processor.py:186} INFO - Started process (PID=306) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T11:59:50.055+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T11:59:50.061+0000] {logging_mixin.py:190} INFO - [2025-01-30T11:59:50.060+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T11:59:50.072+0000] {logging_mixin.py:190} INFO - [2025-01-30T11:59:50.069+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T11:59:50.074+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T11:59:50.109+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.075 seconds
[2025-01-30T12:00:20.390+0000] {processor.py:186} INFO - Started process (PID=313) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T12:00:20.393+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T12:00:20.399+0000] {logging_mixin.py:190} INFO - [2025-01-30T12:00:20.398+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T12:00:20.412+0000] {logging_mixin.py:190} INFO - [2025-01-30T12:00:20.409+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T12:00:20.414+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T12:00:20.453+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.077 seconds
[2025-01-30T12:00:50.755+0000] {processor.py:186} INFO - Started process (PID=320) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T12:00:50.756+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T12:00:50.760+0000] {logging_mixin.py:190} INFO - [2025-01-30T12:00:50.759+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T12:00:50.766+0000] {logging_mixin.py:190} INFO - [2025-01-30T12:00:50.765+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T12:00:50.767+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T12:00:50.790+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.061 seconds
[2025-01-30T12:01:21.105+0000] {processor.py:186} INFO - Started process (PID=327) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T12:01:21.107+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T12:01:21.114+0000] {logging_mixin.py:190} INFO - [2025-01-30T12:01:21.113+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T12:01:21.126+0000] {logging_mixin.py:190} INFO - [2025-01-30T12:01:21.123+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T12:01:21.128+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T12:01:21.168+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.077 seconds
[2025-01-30T12:01:51.443+0000] {processor.py:186} INFO - Started process (PID=334) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T12:01:51.445+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T12:01:51.453+0000] {logging_mixin.py:190} INFO - [2025-01-30T12:01:51.452+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T12:01:51.464+0000] {logging_mixin.py:190} INFO - [2025-01-30T12:01:51.461+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T12:01:51.466+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T12:01:51.510+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.083 seconds
[2025-01-30T12:02:21.827+0000] {processor.py:186} INFO - Started process (PID=341) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T12:02:21.829+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T12:02:21.836+0000] {logging_mixin.py:190} INFO - [2025-01-30T12:02:21.834+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T12:02:21.848+0000] {logging_mixin.py:190} INFO - [2025-01-30T12:02:21.845+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T12:02:21.850+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T12:02:21.891+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.078 seconds
[2025-01-30T12:02:52.161+0000] {processor.py:186} INFO - Started process (PID=348) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T12:02:52.163+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T12:02:52.169+0000] {logging_mixin.py:190} INFO - [2025-01-30T12:02:52.168+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T12:02:52.183+0000] {logging_mixin.py:190} INFO - [2025-01-30T12:02:52.180+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T12:02:52.185+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T12:02:52.230+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.085 seconds
[2025-01-30T12:03:22.515+0000] {processor.py:186} INFO - Started process (PID=355) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T12:03:22.518+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T12:03:22.525+0000] {logging_mixin.py:190} INFO - [2025-01-30T12:03:22.524+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T12:03:22.538+0000] {logging_mixin.py:190} INFO - [2025-01-30T12:03:22.535+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T12:03:22.540+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T12:03:22.570+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.069 seconds
[2025-01-30T12:03:52.853+0000] {processor.py:186} INFO - Started process (PID=362) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T12:03:52.855+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T12:03:52.862+0000] {logging_mixin.py:190} INFO - [2025-01-30T12:03:52.861+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T12:03:52.875+0000] {logging_mixin.py:190} INFO - [2025-01-30T12:03:52.872+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T12:03:52.877+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T12:03:52.920+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.082 seconds
[2025-01-30T12:04:23.207+0000] {processor.py:186} INFO - Started process (PID=369) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T12:04:23.210+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T12:04:23.217+0000] {logging_mixin.py:190} INFO - [2025-01-30T12:04:23.216+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T12:04:23.230+0000] {logging_mixin.py:190} INFO - [2025-01-30T12:04:23.227+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T12:04:23.232+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T12:04:23.270+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.077 seconds
[2025-01-30T12:04:53.549+0000] {processor.py:186} INFO - Started process (PID=376) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T12:04:53.551+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T12:04:53.559+0000] {logging_mixin.py:190} INFO - [2025-01-30T12:04:53.558+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T12:04:53.572+0000] {logging_mixin.py:190} INFO - [2025-01-30T12:04:53.569+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T12:04:53.574+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T12:04:53.616+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.082 seconds
[2025-01-30T12:05:23.894+0000] {processor.py:186} INFO - Started process (PID=382) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T12:05:23.896+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T12:05:23.904+0000] {logging_mixin.py:190} INFO - [2025-01-30T12:05:23.903+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T12:05:23.917+0000] {logging_mixin.py:190} INFO - [2025-01-30T12:05:23.914+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T12:05:23.919+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T12:05:23.964+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.085 seconds
[2025-01-30T12:05:54.246+0000] {processor.py:186} INFO - Started process (PID=389) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T12:05:54.248+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T12:05:54.253+0000] {logging_mixin.py:190} INFO - [2025-01-30T12:05:54.252+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T12:05:54.261+0000] {logging_mixin.py:190} INFO - [2025-01-30T12:05:54.260+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T12:05:54.262+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T12:05:54.289+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.056 seconds
[2025-01-30T12:06:24.580+0000] {processor.py:186} INFO - Started process (PID=396) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T12:06:24.582+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T12:06:24.585+0000] {logging_mixin.py:190} INFO - [2025-01-30T12:06:24.584+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T12:06:24.590+0000] {logging_mixin.py:190} INFO - [2025-01-30T12:06:24.589+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T12:06:24.591+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T12:06:24.620+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.054 seconds
[2025-01-30T12:06:42.828+0000] {processor.py:186} INFO - Started process (PID=397) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T12:06:42.829+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T12:06:42.833+0000] {logging_mixin.py:190} INFO - [2025-01-30T12:06:42.832+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T12:06:42.839+0000] {logging_mixin.py:190} INFO - [2025-01-30T12:06:42.838+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T12:06:42.840+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T12:06:42.867+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.057 seconds
[2025-01-30T12:07:13.140+0000] {processor.py:186} INFO - Started process (PID=404) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T12:07:13.142+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T12:07:13.148+0000] {logging_mixin.py:190} INFO - [2025-01-30T12:07:13.147+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T12:07:13.159+0000] {logging_mixin.py:190} INFO - [2025-01-30T12:07:13.158+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T12:07:13.160+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T12:07:13.187+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.064 seconds
[2025-01-30T12:07:43.559+0000] {processor.py:186} INFO - Started process (PID=411) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T12:07:43.562+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T12:07:43.572+0000] {logging_mixin.py:190} INFO - [2025-01-30T12:07:43.570+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T12:07:43.586+0000] {logging_mixin.py:190} INFO - [2025-01-30T12:07:43.583+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T12:07:43.588+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T12:07:43.631+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.088 seconds
[2025-01-30T13:11:02.895+0000] {processor.py:186} INFO - Started process (PID=414) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T13:11:02.897+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T13:11:02.904+0000] {logging_mixin.py:190} INFO - [2025-01-30T13:11:02.902+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T13:11:02.914+0000] {logging_mixin.py:190} INFO - [2025-01-30T13:11:02.912+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T13:11:02.915+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T13:11:02.956+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.077 seconds
[2025-01-30T13:11:33.285+0000] {processor.py:186} INFO - Started process (PID=421) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T13:11:33.287+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T13:11:33.294+0000] {logging_mixin.py:190} INFO - [2025-01-30T13:11:33.293+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T13:11:33.307+0000] {logging_mixin.py:190} INFO - [2025-01-30T13:11:33.304+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T13:11:33.309+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T13:11:33.349+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.080 seconds
[2025-01-30T13:12:03.669+0000] {processor.py:186} INFO - Started process (PID=428) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T13:12:03.672+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T13:12:03.680+0000] {logging_mixin.py:190} INFO - [2025-01-30T13:12:03.679+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T13:12:03.695+0000] {logging_mixin.py:190} INFO - [2025-01-30T13:12:03.692+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T13:12:03.697+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T13:12:03.748+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.094 seconds
[2025-01-30T13:12:34.088+0000] {processor.py:186} INFO - Started process (PID=435) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T13:12:34.091+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T13:12:34.101+0000] {logging_mixin.py:190} INFO - [2025-01-30T13:12:34.099+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T13:12:34.115+0000] {logging_mixin.py:190} INFO - [2025-01-30T13:12:34.111+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T13:12:34.117+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T13:12:34.162+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.092 seconds
[2025-01-30T13:13:04.486+0000] {processor.py:186} INFO - Started process (PID=442) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T13:13:04.488+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T13:13:04.493+0000] {logging_mixin.py:190} INFO - [2025-01-30T13:13:04.493+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T13:13:04.504+0000] {logging_mixin.py:190} INFO - [2025-01-30T13:13:04.502+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T13:13:04.507+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T13:13:04.547+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.079 seconds
[2025-01-30T13:13:34.886+0000] {processor.py:186} INFO - Started process (PID=449) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T13:13:34.888+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T13:13:34.895+0000] {logging_mixin.py:190} INFO - [2025-01-30T13:13:34.894+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T13:13:34.908+0000] {logging_mixin.py:190} INFO - [2025-01-30T13:13:34.906+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T13:13:34.910+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T13:13:34.955+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.084 seconds
[2025-01-30T13:14:05.284+0000] {processor.py:186} INFO - Started process (PID=456) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T13:14:05.287+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T13:14:05.297+0000] {logging_mixin.py:190} INFO - [2025-01-30T13:14:05.296+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T13:14:05.316+0000] {logging_mixin.py:190} INFO - [2025-01-30T13:14:05.312+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T13:14:05.319+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T13:14:05.370+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.103 seconds
[2025-01-30T13:14:36.324+0000] {processor.py:186} INFO - Started process (PID=463) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T13:14:36.327+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T13:14:36.334+0000] {logging_mixin.py:190} INFO - [2025-01-30T13:14:36.333+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T13:14:36.347+0000] {logging_mixin.py:190} INFO - [2025-01-30T13:14:36.344+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T13:14:36.349+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T13:14:36.396+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.089 seconds
[2025-01-30T13:15:06.704+0000] {processor.py:186} INFO - Started process (PID=470) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T13:15:06.707+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T13:15:06.712+0000] {logging_mixin.py:190} INFO - [2025-01-30T13:15:06.711+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T13:15:06.720+0000] {logging_mixin.py:190} INFO - [2025-01-30T13:15:06.718+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T13:15:06.722+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T13:15:06.759+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.071 seconds
[2025-01-30T13:15:37.096+0000] {processor.py:186} INFO - Started process (PID=476) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T13:15:37.098+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T13:15:37.104+0000] {logging_mixin.py:190} INFO - [2025-01-30T13:15:37.103+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T13:15:37.116+0000] {logging_mixin.py:190} INFO - [2025-01-30T13:15:37.113+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T13:15:37.118+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T13:15:37.163+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.084 seconds
[2025-01-30T13:16:39.150+0000] {processor.py:186} INFO - Started process (PID=483) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T13:16:39.153+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T13:16:39.160+0000] {logging_mixin.py:190} INFO - [2025-01-30T13:16:39.159+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T13:16:39.175+0000] {logging_mixin.py:190} INFO - [2025-01-30T13:16:39.172+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T13:16:39.178+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T13:16:39.227+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.103 seconds
[2025-01-30T13:17:09.520+0000] {processor.py:186} INFO - Started process (PID=496) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T13:17:09.522+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T13:17:09.530+0000] {logging_mixin.py:190} INFO - [2025-01-30T13:17:09.529+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T13:17:09.544+0000] {logging_mixin.py:190} INFO - [2025-01-30T13:17:09.541+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T13:17:09.546+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T13:17:09.594+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.091 seconds
[2025-01-30T13:17:39.964+0000] {processor.py:186} INFO - Started process (PID=503) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T13:17:39.966+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T13:17:39.971+0000] {logging_mixin.py:190} INFO - [2025-01-30T13:17:39.970+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T13:17:39.981+0000] {logging_mixin.py:190} INFO - [2025-01-30T13:17:39.980+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T13:17:39.983+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T13:17:40.026+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.080 seconds
[2025-01-30T13:18:10.355+0000] {processor.py:186} INFO - Started process (PID=510) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T13:18:10.357+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T13:18:10.365+0000] {logging_mixin.py:190} INFO - [2025-01-30T13:18:10.364+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T13:18:10.380+0000] {logging_mixin.py:190} INFO - [2025-01-30T13:18:10.376+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T13:18:10.382+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T13:18:10.433+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.096 seconds
[2025-01-30T13:18:40.771+0000] {processor.py:186} INFO - Started process (PID=517) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T13:18:40.774+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T13:18:40.782+0000] {logging_mixin.py:190} INFO - [2025-01-30T13:18:40.781+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T13:18:40.798+0000] {logging_mixin.py:190} INFO - [2025-01-30T13:18:40.795+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T13:18:40.800+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T13:18:40.842+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.087 seconds
[2025-01-30T14:03:28.222+0000] {processor.py:186} INFO - Started process (PID=524) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:03:28.223+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:03:28.228+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:03:28.227+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:03:28.238+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:03:28.236+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:03:28.240+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:03:28.278+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.070 seconds
[2025-01-30T14:03:58.613+0000] {processor.py:186} INFO - Started process (PID=531) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:03:58.616+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:03:58.623+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:03:58.622+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:03:58.642+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:03:58.637+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:03:58.644+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:03:58.694+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.098 seconds
[2025-01-30T14:04:29.029+0000] {processor.py:186} INFO - Started process (PID=538) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:04:29.031+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:04:29.036+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:04:29.035+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:04:29.045+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:04:29.043+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:04:29.046+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:04:29.096+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.083 seconds
[2025-01-30T14:05:37.827+0000] {processor.py:186} INFO - Started process (PID=89) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:05:37.831+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:05:37.839+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:05:37.837+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:05:37.855+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:05:37.851+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:05:37.857+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:05:37.907+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.105 seconds
[2025-01-30T14:06:08.196+0000] {processor.py:186} INFO - Started process (PID=96) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:06:08.198+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:06:08.205+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:06:08.204+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:06:08.219+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:06:08.217+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:06:08.220+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:06:08.260+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.080 seconds
[2025-01-30T14:06:38.594+0000] {processor.py:186} INFO - Started process (PID=103) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:06:38.596+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:06:38.602+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:06:38.601+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:06:38.612+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:06:38.610+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:06:38.613+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:06:38.654+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.075 seconds
[2025-01-30T14:07:08.974+0000] {processor.py:186} INFO - Started process (PID=110) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:07:08.976+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:07:08.983+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:07:08.982+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:07:08.994+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:07:08.993+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:07:08.996+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:07:09.034+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.076 seconds
[2025-01-30T14:07:39.322+0000] {processor.py:186} INFO - Started process (PID=117) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:07:39.323+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:07:39.330+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:07:39.329+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:07:39.346+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:07:39.341+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:07:39.347+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:07:39.386+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.075 seconds
[2025-01-30T14:08:09.690+0000] {processor.py:186} INFO - Started process (PID=124) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:08:09.692+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:08:09.700+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:08:09.698+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:08:09.717+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:08:09.713+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:08:09.721+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:08:09.775+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.100 seconds
[2025-01-30T14:08:40.071+0000] {processor.py:186} INFO - Started process (PID=131) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:08:40.073+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:08:40.081+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:08:40.080+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:08:40.095+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:08:40.092+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:08:40.097+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:08:40.142+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.086 seconds
[2025-01-30T14:09:10.439+0000] {processor.py:186} INFO - Started process (PID=138) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:09:10.441+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:09:10.447+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:09:10.447+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:09:10.457+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:09:10.455+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:09:10.458+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:09:10.493+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.070 seconds
[2025-01-30T14:09:40.811+0000] {processor.py:186} INFO - Started process (PID=145) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:09:40.813+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:09:40.819+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:09:40.818+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:09:40.830+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:09:40.827+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:09:40.831+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:09:40.871+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.075 seconds
[2025-01-30T14:10:11.139+0000] {processor.py:186} INFO - Started process (PID=152) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:10:11.140+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:10:11.145+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:10:11.144+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:10:11.155+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:10:11.153+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:10:11.157+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:10:11.197+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.070 seconds
[2025-01-30T14:10:41.553+0000] {processor.py:186} INFO - Started process (PID=159) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:10:41.555+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:10:41.561+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:10:41.560+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:10:41.566+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:10:41.565+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:10:41.566+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:10:41.593+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.057 seconds
[2025-01-30T14:11:11.872+0000] {processor.py:186} INFO - Started process (PID=166) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:11:11.873+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:11:11.878+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:11:11.877+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:11:11.885+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:11:11.884+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:11:11.886+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:11:11.910+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.045 seconds
[2025-01-30T14:11:42.216+0000] {processor.py:186} INFO - Started process (PID=173) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:11:42.217+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:11:42.222+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:11:42.221+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:11:42.229+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:11:42.228+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:11:42.230+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:11:42.268+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.068 seconds
[2025-01-30T14:12:12.550+0000] {processor.py:186} INFO - Started process (PID=180) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:12:12.552+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:12:12.555+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:12:12.555+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:12:12.568+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:12:12.566+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:12:12.570+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:12:12.606+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.071 seconds
[2025-01-30T14:12:42.909+0000] {processor.py:186} INFO - Started process (PID=186) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:12:42.910+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:12:42.917+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:12:42.916+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:12:42.926+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:12:42.925+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:12:42.926+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:12:42.955+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.064 seconds
[2025-01-30T14:13:13.233+0000] {processor.py:186} INFO - Started process (PID=193) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:13:13.235+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:13:13.241+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:13:13.240+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:13:13.255+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:13:13.252+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:13:13.258+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:13:13.287+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.069 seconds
[2025-01-30T14:13:43.568+0000] {processor.py:186} INFO - Started process (PID=200) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:13:43.571+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:13:43.577+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:13:43.577+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:13:43.589+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:13:43.586+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:13:43.590+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:13:43.632+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.079 seconds
[2025-01-30T14:14:13.900+0000] {processor.py:186} INFO - Started process (PID=213) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:14:13.902+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:14:13.906+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:14:13.906+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:14:13.913+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:14:13.910+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:14:13.914+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:14:13.939+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.054 seconds
[2025-01-30T14:14:44.248+0000] {processor.py:186} INFO - Started process (PID=220) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:14:44.249+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:14:44.256+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:14:44.256+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:14:44.262+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:14:44.261+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:14:44.263+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:14:44.292+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.057 seconds
[2025-01-30T14:15:14.578+0000] {processor.py:186} INFO - Started process (PID=227) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:15:14.580+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:15:14.586+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:15:14.585+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:15:14.599+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:15:14.596+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:15:14.600+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:15:14.625+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.060 seconds
[2025-01-30T14:15:44.954+0000] {processor.py:186} INFO - Started process (PID=234) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:15:44.955+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:15:44.962+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:15:44.961+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:15:44.971+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:15:44.968+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:15:44.972+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:15:44.997+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.056 seconds
[2025-01-30T14:16:15.298+0000] {processor.py:186} INFO - Started process (PID=241) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:16:15.300+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:16:15.306+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:16:15.305+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:16:15.315+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:16:15.313+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:16:15.317+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:16:15.350+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.067 seconds
[2025-01-30T14:16:45.625+0000] {processor.py:186} INFO - Started process (PID=248) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:16:45.627+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:16:45.632+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:16:45.631+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:16:45.643+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:16:45.641+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:16:45.644+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:16:45.674+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.060 seconds
[2025-01-30T14:17:15.968+0000] {processor.py:186} INFO - Started process (PID=255) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:17:15.968+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:17:15.973+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:17:15.972+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:17:15.984+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:17:15.982+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:17:15.986+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:17:16.015+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.054 seconds
[2025-01-30T14:17:46.319+0000] {processor.py:186} INFO - Started process (PID=262) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:17:46.320+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:17:46.324+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:17:46.324+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:17:46.334+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:17:46.332+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:17:46.335+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:17:46.367+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.056 seconds
[2025-01-30T14:18:16.649+0000] {processor.py:186} INFO - Started process (PID=269) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:18:16.651+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:18:16.655+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:18:16.655+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:18:16.664+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:18:16.662+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:18:16.665+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:18:16.702+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.066 seconds
[2025-01-30T14:18:47.006+0000] {processor.py:186} INFO - Started process (PID=276) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:18:47.007+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:18:47.014+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:18:47.013+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:18:47.021+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:18:47.020+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:18:47.022+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:18:47.047+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.059 seconds
[2025-01-30T14:19:17.337+0000] {processor.py:186} INFO - Started process (PID=283) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:19:17.339+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:19:17.346+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:19:17.345+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:19:17.356+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:19:17.353+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:19:17.358+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:19:17.386+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.063 seconds
[2025-01-30T14:19:47.689+0000] {processor.py:186} INFO - Started process (PID=290) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:19:47.690+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:19:47.693+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:19:47.692+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:19:47.699+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:19:47.698+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:19:47.699+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:19:47.724+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.054 seconds
[2025-01-30T14:20:18.029+0000] {processor.py:186} INFO - Started process (PID=297) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:20:18.031+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:20:18.037+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:20:18.036+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:20:18.043+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:20:18.042+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:20:18.044+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:20:18.073+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.059 seconds
[2025-01-30T14:20:48.403+0000] {processor.py:186} INFO - Started process (PID=304) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:20:48.405+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:20:48.412+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:20:48.411+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:20:48.424+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:20:48.422+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:20:48.426+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:20:48.457+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.067 seconds
[2025-01-30T14:21:18.733+0000] {processor.py:186} INFO - Started process (PID=311) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:21:18.734+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:21:18.740+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:21:18.739+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:21:18.746+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:21:18.745+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:21:18.747+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:21:18.782+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.063 seconds
[2025-01-30T14:21:49.105+0000] {processor.py:186} INFO - Started process (PID=318) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:21:49.107+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:21:49.111+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:21:49.111+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:21:49.125+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:21:49.123+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:21:49.125+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:21:49.153+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.061 seconds
[2025-01-30T14:22:19.430+0000] {processor.py:186} INFO - Started process (PID=325) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:22:19.431+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:22:19.437+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:22:19.435+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:22:19.452+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:22:19.450+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:22:19.455+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:22:19.494+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.070 seconds
[2025-01-30T14:22:49.774+0000] {processor.py:186} INFO - Started process (PID=332) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:22:49.776+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:22:49.784+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:22:49.783+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:22:49.796+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:22:49.792+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:22:49.798+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:22:49.834+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.074 seconds
[2025-01-30T14:23:20.116+0000] {processor.py:186} INFO - Started process (PID=339) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:23:20.119+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:23:20.125+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:23:20.125+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:23:20.139+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:23:20.134+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:23:20.141+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:23:20.164+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.056 seconds
[2025-01-30T14:23:50.472+0000] {processor.py:186} INFO - Started process (PID=346) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:23:50.473+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:23:50.479+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:23:50.477+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:23:50.489+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:23:50.487+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:23:50.491+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:23:50.519+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.062 seconds
[2025-01-30T14:24:20.816+0000] {processor.py:186} INFO - Started process (PID=353) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:24:20.818+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:24:20.825+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:24:20.825+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:24:20.836+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:24:20.832+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:24:20.838+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:24:20.870+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.067 seconds
[2025-01-30T14:24:51.147+0000] {processor.py:186} INFO - Started process (PID=360) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:24:51.148+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:24:51.152+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:24:51.151+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:24:51.158+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:24:51.156+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:24:51.161+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:24:51.193+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.059 seconds
[2025-01-30T14:25:21.481+0000] {processor.py:186} INFO - Started process (PID=367) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:25:21.482+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:25:21.490+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:25:21.489+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:25:21.496+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:25:21.495+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:25:21.497+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:25:21.535+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.072 seconds
[2025-01-30T14:25:51.856+0000] {processor.py:186} INFO - Started process (PID=374) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:25:51.858+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:25:51.865+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:25:51.864+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:25:51.875+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:25:51.873+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:25:51.877+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:25:51.902+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.063 seconds
[2025-01-30T14:26:22.194+0000] {processor.py:186} INFO - Started process (PID=381) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:26:22.195+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:26:22.204+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:26:22.202+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:26:22.211+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:26:22.210+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:26:22.212+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:26:22.246+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.066 seconds
[2025-01-30T14:26:52.543+0000] {processor.py:186} INFO - Started process (PID=387) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:26:52.545+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:26:52.548+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:26:52.547+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:26:52.553+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:26:52.552+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:26:52.554+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:26:52.583+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.053 seconds
[2025-01-30T14:27:22.901+0000] {processor.py:186} INFO - Started process (PID=394) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:27:22.903+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:27:22.908+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:27:22.907+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:27:22.918+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:27:22.915+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:27:22.922+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:27:22.963+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.074 seconds
[2025-01-30T14:27:53.247+0000] {processor.py:186} INFO - Started process (PID=401) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:27:53.248+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:27:53.252+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:27:53.252+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:27:53.268+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:27:53.267+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:27:53.270+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:27:53.299+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.063 seconds
[2025-01-30T14:28:23.616+0000] {processor.py:186} INFO - Started process (PID=408) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:28:23.617+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:28:23.620+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:28:23.620+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:28:23.625+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:28:23.624+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:28:23.626+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:28:23.656+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.059 seconds
[2025-01-30T14:28:53.958+0000] {processor.py:186} INFO - Started process (PID=415) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:28:53.960+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:28:53.963+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:28:53.962+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:28:53.967+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:28:53.966+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:28:53.967+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:28:53.999+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.052 seconds
[2025-01-30T14:29:24.284+0000] {processor.py:186} INFO - Started process (PID=422) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:29:24.286+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:29:24.293+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:29:24.292+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:29:24.305+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:29:24.302+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:29:24.307+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:29:24.340+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.071 seconds
[2025-01-30T14:29:54.652+0000] {processor.py:186} INFO - Started process (PID=429) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:29:54.655+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:29:54.663+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:29:54.662+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:29:54.672+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:29:54.670+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:29:54.673+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:29:54.702+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.066 seconds
[2025-01-30T14:30:24.992+0000] {processor.py:186} INFO - Started process (PID=436) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:30:24.993+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:30:25.002+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:30:25.001+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:30:25.010+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:30:25.007+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:30:25.011+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:30:25.045+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.070 seconds
[2025-01-30T14:30:55.382+0000] {processor.py:186} INFO - Started process (PID=443) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:30:55.383+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:30:55.388+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:30:55.387+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:30:55.396+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:30:55.395+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:30:55.397+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:30:55.429+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.061 seconds
[2025-01-30T14:31:25.717+0000] {processor.py:186} INFO - Started process (PID=450) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:31:25.719+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:31:25.724+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:31:25.723+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:31:25.735+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:31:25.733+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:31:25.736+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:31:25.766+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.064 seconds
[2025-01-30T14:31:56.048+0000] {processor.py:186} INFO - Started process (PID=457) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:31:56.050+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:31:56.058+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:31:56.057+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:31:56.067+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:31:56.065+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:31:56.069+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:31:56.099+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.064 seconds
[2025-01-30T14:32:26.367+0000] {processor.py:186} INFO - Started process (PID=464) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:32:26.368+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:32:26.374+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:32:26.373+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:32:26.387+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:32:26.384+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:32:26.388+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:32:26.432+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.074 seconds
[2025-01-30T14:32:56.745+0000] {processor.py:186} INFO - Started process (PID=471) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:32:56.747+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:32:56.754+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:32:56.753+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:32:56.762+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:32:56.761+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:32:56.763+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:32:56.792+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.061 seconds
[2025-01-30T14:33:27.074+0000] {processor.py:186} INFO - Started process (PID=478) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:33:27.075+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:33:27.084+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:33:27.083+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:33:27.098+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:33:27.095+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:33:27.099+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:33:27.132+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.073 seconds
[2025-01-30T14:33:57.440+0000] {processor.py:186} INFO - Started process (PID=485) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:33:57.442+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:33:57.445+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:33:57.445+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:33:57.451+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:33:57.450+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:33:57.453+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:33:57.480+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.053 seconds
[2025-01-30T14:34:27.793+0000] {processor.py:186} INFO - Started process (PID=491) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:34:27.796+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:34:27.803+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:34:27.802+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:34:27.809+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:34:27.808+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:34:27.809+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:34:27.836+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.060 seconds
[2025-01-30T14:34:58.124+0000] {processor.py:186} INFO - Started process (PID=498) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:34:58.126+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:34:58.130+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:34:58.129+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:34:58.138+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:34:58.137+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:34:58.139+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:34:58.171+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.060 seconds
[2025-01-30T14:35:28.469+0000] {processor.py:186} INFO - Started process (PID=505) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:35:28.471+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:35:28.479+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:35:28.477+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:35:28.487+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:35:28.484+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:35:28.489+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:35:28.529+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.075 seconds
[2025-01-30T14:35:58.861+0000] {processor.py:186} INFO - Started process (PID=511) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:35:58.863+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:35:58.870+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:35:58.869+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:35:58.880+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:35:58.879+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:35:58.880+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:35:58.908+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.064 seconds
[2025-01-30T14:36:29.193+0000] {processor.py:186} INFO - Started process (PID=518) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:36:29.195+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:36:29.203+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:36:29.201+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:36:29.217+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:36:29.214+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:36:29.219+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:36:29.254+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.077 seconds
[2025-01-30T14:36:59.557+0000] {processor.py:186} INFO - Started process (PID=525) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:36:59.558+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:36:59.562+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:36:59.561+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:36:59.568+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:36:59.566+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:36:59.569+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:36:59.604+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.061 seconds
[2025-01-30T14:37:29.880+0000] {processor.py:186} INFO - Started process (PID=532) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:37:29.881+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:37:29.888+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:37:29.888+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:37:29.900+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:37:29.899+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:37:29.901+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:37:29.933+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.068 seconds
[2025-01-30T14:38:00.622+0000] {processor.py:186} INFO - Started process (PID=538) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:38:00.624+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:38:00.631+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:38:00.630+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:38:00.637+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:38:00.636+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:38:00.638+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:38:00.667+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.061 seconds
[2025-01-30T14:38:30.941+0000] {processor.py:186} INFO - Started process (PID=545) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:38:30.943+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:38:30.948+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:38:30.948+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:38:30.957+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:38:30.956+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:38:30.958+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:38:30.994+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.063 seconds
[2025-01-30T14:39:01.285+0000] {processor.py:186} INFO - Started process (PID=552) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:39:01.287+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:39:01.293+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:39:01.292+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:39:01.303+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:39:01.302+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:39:01.304+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:39:01.336+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.062 seconds
[2025-01-30T14:39:41.674+0000] {processor.py:186} INFO - Started process (PID=559) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:39:41.675+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:39:41.685+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:39:41.684+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:39:41.700+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:39:41.697+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:39:41.703+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:39:41.743+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.086 seconds
[2025-01-30T14:40:12.007+0000] {processor.py:186} INFO - Started process (PID=566) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:40:12.009+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:40:12.016+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:40:12.015+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:40:12.030+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:40:12.027+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:40:12.032+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:40:12.074+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.082 seconds
[2025-01-30T14:40:42.391+0000] {processor.py:186} INFO - Started process (PID=573) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:40:42.392+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:40:42.397+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:40:42.397+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:40:42.406+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:40:42.405+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:40:42.408+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:40:42.435+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.055 seconds
[2025-01-30T14:41:12.726+0000] {processor.py:186} INFO - Started process (PID=580) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:41:12.727+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:41:12.733+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:41:12.732+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:41:12.743+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:41:12.741+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:41:12.745+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:41:12.777+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.060 seconds
[2025-01-30T14:41:43.067+0000] {processor.py:186} INFO - Started process (PID=587) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:41:43.069+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:41:43.075+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:41:43.074+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:41:43.086+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:41:43.083+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/http_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/http_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2025-01-30T14:41:43.088+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:41:43.119+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.070 seconds
[2025-01-30T14:42:00.601+0000] {processor.py:186} INFO - Started process (PID=594) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:42:00.602+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:42:00.607+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:42:00.606+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:42:02.577+0000] {processor.py:925} INFO - DAG(s) 'http_dag' retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:42:03.003+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:42:03.002+0000] {override.py:1911} INFO - Created Permission View: can read on DAG:http_dag
[2025-01-30T14:42:03.017+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:42:03.017+0000] {override.py:1911} INFO - Created Permission View: can delete on DAG:http_dag
[2025-01-30T14:42:03.029+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:42:03.029+0000] {override.py:1911} INFO - Created Permission View: can edit on DAG:http_dag
[2025-01-30T14:42:03.044+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:42:03.043+0000] {override.py:1911} INFO - Created Permission View: menu access on DAG Run:http_dag
[2025-01-30T14:42:03.056+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:42:03.055+0000] {override.py:1911} INFO - Created Permission View: can read on DAG Run:http_dag
[2025-01-30T14:42:03.072+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:42:03.071+0000] {override.py:1911} INFO - Created Permission View: can delete on DAG Run:http_dag
[2025-01-30T14:42:03.087+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:42:03.086+0000] {override.py:1911} INFO - Created Permission View: can create on DAG Run:http_dag
[2025-01-30T14:42:03.089+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:42:03.088+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T14:42:03.106+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:42:03.106+0000] {dag.py:3262} INFO - Creating ORM DAG for http_dag
[2025-01-30T14:42:03.117+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:42:03.117+0000] {dag.py:4180} INFO - Setting next_dagrun for http_dag to 2025-01-29 00:00:00+00:00, run_after=2025-01-30 00:00:00+00:00
[2025-01-30T14:42:03.142+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 2.548 seconds
[2025-01-30T14:42:33.453+0000] {processor.py:186} INFO - Started process (PID=602) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:42:33.455+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:42:33.461+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:42:33.460+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:42:33.923+0000] {processor.py:925} INFO - DAG(s) 'http_dag' retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:42:33.969+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:42:33.968+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T14:42:33.997+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:42:33.997+0000] {dag.py:4180} INFO - Setting next_dagrun for http_dag to 2025-01-29 00:00:00+00:00, run_after=2025-01-30 00:00:00+00:00
[2025-01-30T14:42:34.019+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.580 seconds
[2025-01-30T14:43:04.163+0000] {processor.py:186} INFO - Started process (PID=610) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:43:04.167+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:43:04.174+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:43:04.173+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:43:04.995+0000] {processor.py:925} INFO - DAG(s) 'http_dag' retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:43:05.030+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:43:05.030+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T14:43:05.063+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:43:05.063+0000] {dag.py:4180} INFO - Setting next_dagrun for http_dag to 2025-01-30 00:00:00+00:00, run_after=2025-01-31 00:00:00+00:00
[2025-01-30T14:43:05.094+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.948 seconds
[2025-01-30T14:43:35.445+0000] {processor.py:186} INFO - Started process (PID=618) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:43:35.448+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:43:35.654+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:43:35.654+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:43:36.042+0000] {processor.py:925} INFO - DAG(s) 'http_dag' retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:43:36.073+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:43:36.072+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T14:43:36.103+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:43:36.103+0000] {dag.py:4180} INFO - Setting next_dagrun for http_dag to 2025-01-30 00:00:00+00:00, run_after=2025-01-31 00:00:00+00:00
[2025-01-30T14:43:36.138+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.708 seconds
[2025-01-30T14:44:06.492+0000] {processor.py:186} INFO - Started process (PID=626) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:44:06.494+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:44:06.500+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:44:06.499+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:44:06.791+0000] {processor.py:925} INFO - DAG(s) 'http_dag' retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:44:06.818+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:44:06.818+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T14:44:06.844+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:44:06.843+0000] {dag.py:4180} INFO - Setting next_dagrun for http_dag to 2025-01-30 00:00:00+00:00, run_after=2025-01-31 00:00:00+00:00
[2025-01-30T14:44:06.867+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.391 seconds
[2025-01-30T14:44:37.216+0000] {processor.py:186} INFO - Started process (PID=634) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:44:37.219+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:44:37.224+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:44:37.224+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:44:37.573+0000] {processor.py:925} INFO - DAG(s) 'http_dag' retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:44:37.603+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:44:37.603+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T14:44:37.628+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:44:37.628+0000] {dag.py:4180} INFO - Setting next_dagrun for http_dag to 2025-01-30 00:00:00+00:00, run_after=2025-01-31 00:00:00+00:00
[2025-01-30T14:44:37.653+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.453 seconds
[2025-01-30T14:45:08.004+0000] {processor.py:186} INFO - Started process (PID=641) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:45:08.007+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:45:08.014+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:45:08.012+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:45:08.319+0000] {processor.py:925} INFO - DAG(s) 'http_dag' retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:45:08.347+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:45:08.346+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T14:45:08.372+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:45:08.372+0000] {dag.py:4180} INFO - Setting next_dagrun for http_dag to 2025-01-30 00:00:00+00:00, run_after=2025-01-31 00:00:00+00:00
[2025-01-30T14:45:08.396+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.407 seconds
[2025-01-30T14:45:38.722+0000] {processor.py:186} INFO - Started process (PID=648) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:45:38.724+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:45:38.729+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:45:38.728+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:45:39.042+0000] {processor.py:925} INFO - DAG(s) 'http_dag' retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:45:39.073+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:45:39.072+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T14:45:39.101+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:45:39.101+0000] {dag.py:4180} INFO - Setting next_dagrun for http_dag to 2025-01-30 00:00:00+00:00, run_after=2025-01-31 00:00:00+00:00
[2025-01-30T14:45:39.124+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.418 seconds
[2025-01-30T14:46:09.433+0000] {processor.py:186} INFO - Started process (PID=658) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:46:09.435+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:46:09.439+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:46:09.438+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:46:09.732+0000] {processor.py:925} INFO - DAG(s) 'http_dag' retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:46:09.761+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:46:09.760+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T14:46:09.793+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:46:09.792+0000] {dag.py:4180} INFO - Setting next_dagrun for http_dag to 2025-01-30 00:00:00+00:00, run_after=2025-01-31 00:00:00+00:00
[2025-01-30T14:46:09.821+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.403 seconds
[2025-01-30T14:46:39.926+0000] {processor.py:186} INFO - Started process (PID=668) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:46:39.928+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:46:39.933+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:46:39.933+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:46:40.200+0000] {processor.py:925} INFO - DAG(s) 'http_dag' retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:46:40.224+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:46:40.223+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T14:46:40.250+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:46:40.250+0000] {dag.py:4180} INFO - Setting next_dagrun for http_dag to 2025-01-30 00:00:00+00:00, run_after=2025-01-31 00:00:00+00:00
[2025-01-30T14:46:40.273+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.359 seconds
[2025-01-30T14:47:10.450+0000] {processor.py:186} INFO - Started process (PID=678) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:47:10.453+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:47:10.460+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:47:10.459+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:47:10.748+0000] {processor.py:925} INFO - DAG(s) 'http_dag' retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:47:10.777+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:47:10.776+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T14:47:10.804+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:47:10.804+0000] {dag.py:4180} INFO - Setting next_dagrun for http_dag to 2025-01-30 00:00:00+00:00, run_after=2025-01-31 00:00:00+00:00
[2025-01-30T14:47:10.830+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.394 seconds
[2025-01-30T14:47:40.961+0000] {processor.py:186} INFO - Started process (PID=688) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:47:40.964+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:47:40.970+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:47:40.970+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:47:41.286+0000] {processor.py:925} INFO - DAG(s) 'http_dag' retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:47:41.313+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:47:41.312+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T14:47:41.337+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:47:41.337+0000] {dag.py:4180} INFO - Setting next_dagrun for http_dag to 2025-01-30 00:00:00+00:00, run_after=2025-01-31 00:00:00+00:00
[2025-01-30T14:47:41.359+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.412 seconds
[2025-01-30T14:47:51.301+0000] {processor.py:186} INFO - Started process (PID=692) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:47:51.303+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:47:51.309+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:47:51.308+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:47:51.629+0000] {processor.py:925} INFO - DAG(s) 'http_dag' retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:47:51.658+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:47:51.657+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T14:47:51.683+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:47:51.682+0000] {dag.py:4180} INFO - Setting next_dagrun for http_dag to 2025-01-30 00:00:00+00:00, run_after=2025-01-31 00:00:00+00:00
[2025-01-30T14:47:51.716+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.430 seconds
[2025-01-30T14:48:21.835+0000] {processor.py:186} INFO - Started process (PID=708) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:48:21.838+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:48:21.844+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:48:21.844+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:48:22.254+0000] {processor.py:925} INFO - DAG(s) 'http_dag' retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:48:22.286+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:48:22.285+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T14:48:22.313+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:48:22.313+0000] {dag.py:4180} INFO - Setting next_dagrun for http_dag to 2025-01-30 00:00:00+00:00, run_after=2025-01-31 00:00:00+00:00
[2025-01-30T14:48:22.339+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.518 seconds
[2025-01-30T14:48:53.364+0000] {processor.py:186} INFO - Started process (PID=718) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:48:53.366+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:48:53.373+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:48:53.372+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:48:53.755+0000] {processor.py:925} INFO - DAG(s) 'http_dag' retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:48:53.781+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:48:53.781+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T14:48:53.811+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:48:53.810+0000] {dag.py:4180} INFO - Setting next_dagrun for http_dag to 2025-01-30 00:00:00+00:00, run_after=2025-01-31 00:00:00+00:00
[2025-01-30T14:48:53.834+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.486 seconds
[2025-01-30T14:49:24.884+0000] {processor.py:186} INFO - Started process (PID=728) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:49:24.886+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:49:24.893+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:49:24.892+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:49:25.259+0000] {processor.py:925} INFO - DAG(s) 'http_dag' retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:49:25.285+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:49:25.285+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T14:49:25.313+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:49:25.313+0000] {dag.py:4180} INFO - Setting next_dagrun for http_dag to 2025-01-30 00:00:00+00:00, run_after=2025-01-31 00:00:00+00:00
[2025-01-30T14:49:25.337+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.467 seconds
[2025-01-30T14:49:55.407+0000] {processor.py:186} INFO - Started process (PID=738) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:49:55.410+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:49:55.416+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:49:55.416+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:49:55.781+0000] {processor.py:925} INFO - DAG(s) 'http_dag' retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:49:55.811+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:49:55.810+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T14:49:55.839+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:49:55.838+0000] {dag.py:4180} INFO - Setting next_dagrun for http_dag to 2025-01-30 00:00:00+00:00, run_after=2025-01-31 00:00:00+00:00
[2025-01-30T14:49:55.863+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.471 seconds
[2025-01-30T14:50:03.523+0000] {processor.py:186} INFO - Started process (PID=740) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:50:03.525+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:50:03.529+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:50:03.528+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:50:03.875+0000] {processor.py:925} INFO - DAG(s) 'http_dag' retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:50:03.922+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:50:03.921+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T14:50:03.962+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:50:03.962+0000] {dag.py:4180} INFO - Setting next_dagrun for http_dag to 2025-01-30 00:00:00+00:00, run_after=2025-01-31 00:00:00+00:00
[2025-01-30T14:50:03.994+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.487 seconds
[2025-01-30T14:50:34.545+0000] {processor.py:186} INFO - Started process (PID=750) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:50:34.547+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:50:34.554+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:50:34.553+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:50:34.891+0000] {processor.py:925} INFO - DAG(s) 'http_dag' retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:50:34.925+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:50:34.925+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T14:50:34.956+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:50:34.956+0000] {dag.py:4180} INFO - Setting next_dagrun for http_dag to 2025-01-30 00:00:00+00:00, run_after=2025-01-31 00:00:00+00:00
[2025-01-30T14:50:34.982+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.451 seconds
[2025-01-30T14:51:05.235+0000] {processor.py:186} INFO - Started process (PID=760) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:51:05.236+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:51:05.244+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:51:05.244+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:51:05.567+0000] {processor.py:925} INFO - DAG(s) 'http_dag' retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:51:05.599+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:51:05.599+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T14:51:05.627+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:51:05.627+0000] {dag.py:4180} INFO - Setting next_dagrun for http_dag to 2025-01-30 00:00:00+00:00, run_after=2025-01-31 00:00:00+00:00
[2025-01-30T14:51:05.652+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.424 seconds
[2025-01-30T14:51:35.819+0000] {processor.py:186} INFO - Started process (PID=770) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:51:35.822+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:51:35.828+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:51:35.827+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:51:36.162+0000] {processor.py:925} INFO - DAG(s) 'http_dag' retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:51:36.193+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:51:36.192+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T14:51:36.223+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:51:36.223+0000] {dag.py:4180} INFO - Setting next_dagrun for http_dag to 2025-01-30 00:00:00+00:00, run_after=2025-01-31 00:00:00+00:00
[2025-01-30T14:51:36.250+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.444 seconds
[2025-01-30T14:52:06.372+0000] {processor.py:186} INFO - Started process (PID=780) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:52:06.375+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:52:06.382+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:52:06.381+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:52:06.694+0000] {processor.py:925} INFO - DAG(s) 'http_dag' retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:52:06.723+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:52:06.722+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T14:52:06.754+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:52:06.754+0000] {dag.py:4180} INFO - Setting next_dagrun for http_dag to 2025-01-30 00:00:00+00:00, run_after=2025-01-31 00:00:00+00:00
[2025-01-30T14:52:06.781+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.423 seconds
[2025-01-30T14:52:36.927+0000] {processor.py:186} INFO - Started process (PID=790) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:52:36.929+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:52:36.936+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:52:36.935+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:52:37.240+0000] {processor.py:925} INFO - DAG(s) 'http_dag' retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:52:37.271+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:52:37.270+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T14:52:37.300+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:52:37.299+0000] {dag.py:4180} INFO - Setting next_dagrun for http_dag to 2025-01-30 00:00:00+00:00, run_after=2025-01-31 00:00:00+00:00
[2025-01-30T14:52:37.326+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.413 seconds
[2025-01-30T14:53:07.515+0000] {processor.py:186} INFO - Started process (PID=799) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:53:07.517+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:53:07.525+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:53:07.524+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:53:07.823+0000] {processor.py:925} INFO - DAG(s) 'http_dag' retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:53:07.850+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:53:07.849+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T14:53:07.873+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:53:07.873+0000] {dag.py:4180} INFO - Setting next_dagrun for http_dag to 2025-01-30 00:00:00+00:00, run_after=2025-01-31 00:00:00+00:00
[2025-01-30T14:53:07.895+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.395 seconds
[2025-01-30T14:53:37.988+0000] {processor.py:186} INFO - Started process (PID=809) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:53:37.991+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:53:38.000+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:53:37.999+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:53:38.301+0000] {processor.py:925} INFO - DAG(s) 'http_dag' retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:53:38.330+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:53:38.330+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T14:53:38.355+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:53:38.354+0000] {dag.py:4180} INFO - Setting next_dagrun for http_dag to 2025-01-30 00:00:00+00:00, run_after=2025-01-31 00:00:00+00:00
[2025-01-30T14:53:38.380+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.407 seconds
[2025-01-30T14:54:08.497+0000] {processor.py:186} INFO - Started process (PID=819) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:54:08.499+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:54:08.505+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:54:08.504+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:54:08.865+0000] {processor.py:925} INFO - DAG(s) 'http_dag' retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:54:08.894+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:54:08.893+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T14:54:08.920+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:54:08.920+0000] {dag.py:4180} INFO - Setting next_dagrun for http_dag to 2025-01-30 00:00:00+00:00, run_after=2025-01-31 00:00:00+00:00
[2025-01-30T14:54:08.941+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.456 seconds
[2025-01-30T14:54:39.010+0000] {processor.py:186} INFO - Started process (PID=829) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:54:39.012+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:54:39.016+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:54:39.016+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:54:39.307+0000] {processor.py:925} INFO - DAG(s) 'http_dag' retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:54:39.334+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:54:39.333+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T14:54:39.358+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:54:39.358+0000] {dag.py:4180} INFO - Setting next_dagrun for http_dag to 2025-01-30 00:00:00+00:00, run_after=2025-01-31 00:00:00+00:00
[2025-01-30T14:54:39.383+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.389 seconds
[2025-01-30T14:55:09.530+0000] {processor.py:186} INFO - Started process (PID=839) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:55:09.532+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:55:09.538+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:55:09.537+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:55:09.842+0000] {processor.py:925} INFO - DAG(s) 'http_dag' retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:55:09.870+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:55:09.870+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T14:55:09.903+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:55:09.902+0000] {dag.py:4180} INFO - Setting next_dagrun for http_dag to 2025-01-30 00:00:00+00:00, run_after=2025-01-31 00:00:00+00:00
[2025-01-30T14:55:09.939+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.420 seconds
[2025-01-30T14:55:40.044+0000] {processor.py:186} INFO - Started process (PID=849) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:55:40.046+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:55:40.050+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:55:40.049+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:55:40.332+0000] {processor.py:925} INFO - DAG(s) 'http_dag' retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:55:40.357+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:55:40.357+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T14:55:40.383+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:55:40.383+0000] {dag.py:4180} INFO - Setting next_dagrun for http_dag to 2025-01-30 00:00:00+00:00, run_after=2025-01-31 00:00:00+00:00
[2025-01-30T14:55:40.405+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.370 seconds
[2025-01-30T14:56:10.586+0000] {processor.py:186} INFO - Started process (PID=859) to work on /opt/airflow/dags/http_dag.py
[2025-01-30T14:56:10.589+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/http_dag.py for tasks to queue
[2025-01-30T14:56:10.595+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:56:10.594+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/http_dag.py
[2025-01-30T14:56:10.880+0000] {processor.py:925} INFO - DAG(s) 'http_dag' retrieved from /opt/airflow/dags/http_dag.py
[2025-01-30T14:56:10.906+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:56:10.905+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T14:56:10.931+0000] {logging_mixin.py:190} INFO - [2025-01-30T14:56:10.930+0000] {dag.py:4180} INFO - Setting next_dagrun for http_dag to 2025-01-30 00:00:00+00:00, run_after=2025-01-31 00:00:00+00:00
[2025-01-30T14:56:10.952+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/http_dag.py took 0.381 seconds
